name: GroupBot
main: com.google.android.groupbot
website: www.groupbotmc.com
version: 1.0.2 Alpha 
commands:
 hi:
  description: sends a message of "hi" to a player
 gp: 
  description: Opens the GroupBot plugin help menu 